'''
add folder model

Revision ID: 029849e6bb05
Created at: 2024-12-28 07:52:54.829387
'''

import sqlalchemy as sa
from alembic import op



revision = '029849e6bb05'
down_revision = '2ec27ff621ce'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=False),
    sa.Column('description', sa.Unicode(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.Unicode(length=2048), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['folder.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'folder', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
