'''
fill gaps

Revision ID: 2ec27ff621ce
Created at: 2024-12-28 07:33:11.801197
'''

import sqlalchemy as sa
from alembic import op



revision = '2ec27ff621ce'
down_revision = '0c149800a728'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pool_category_id'), 'pool', ['category_id'], unique=False)
    op.alter_column('pool_name', 'name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Unicode(length=128),
               existing_nullable=False)
    op.create_index(op.f('ix_pool_name_pool_id'), 'pool_name', ['pool_id'], unique=False)
    op.create_index(op.f('ix_pool_post_pool_id'), 'pool_post', ['pool_id'], unique=False)
    op.drop_constraint('pool_post_pool_id_fkey', 'pool_post', type_='foreignkey')
    op.drop_constraint('pool_post_post_id_fkey', 'pool_post', type_='foreignkey')
    op.create_foreign_key(None, 'pool_post', 'pool', ['pool_id'], ['id'])
    op.create_foreign_key(None, 'pool_post', 'post', ['post_id'], ['id'])
    op.create_index(op.f('ix_post_signature_post_id'), 'post_signature', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_signature_words'), 'post_signature', ['words'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_signature_words'), table_name='post_signature')
    op.drop_index(op.f('ix_post_signature_post_id'), table_name='post_signature')
    op.drop_constraint(None, 'pool_post', type_='foreignkey')
    op.drop_constraint(None, 'pool_post', type_='foreignkey')
    op.create_foreign_key('pool_post_post_id_fkey', 'pool_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pool_post_pool_id_fkey', 'pool_post', 'pool', ['pool_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pool_post_pool_id'), table_name='pool_post')
    op.drop_index(op.f('ix_pool_name_pool_id'), table_name='pool_name')
    op.alter_column('pool_name', 'name',
               existing_type=sa.Unicode(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_index(op.f('ix_pool_category_id'), table_name='pool')
    # ### end Alembic commands ###
